### ISSUE TITLE
No binary after build

### ISSUE THREAD

**Issue by vsiles** [andreypopp/merlin#2]
Hi ! I'm trying to build ocamlmerlin-lsp and I'm very new to esy. I did the following sequence:
```
npm install -g esy@0.5.x
esy
```

Which triggered a bunch of dependency compilation, ending with
```
$ esy
info esy 0.5.4 (using package.json)
info fetching: done
info installing: done
info building @esy-ocaml/substs@0.0.1@d41d8cd9
info building ocaml@4.6.9@d41d8cd9
... snip 8< ... snip 8< ...
info building @opam/ppx_deriving_yojson@opam:3.3@9029495a: done
info building @opam/merlin@opam:3.2.2@829ee6dd: done
info building @opam/utop@opam:2.2.0@82198b0d: done
```

and now I can't find any binary. I have a `_esy` directory but there is not much in it. Am I missing something ?

**Comment by andreypopp** [comment]
Run `esy make`, I'm using esy but trying to keep the workflow close to original opam's merlin's so it's easier to upstream.

**Comment by vsiles** [comment]
Works like a charm ! Thanks and sorry for the noob question :)

**Comment by andreypopp** [comment]
No problem! I've updated the README to reflect the latest changes.

Curious what editor do you use?

**Comment by vsiles** [comment]
vim + merlin without lsp :D @jordwalke pointed me here to see if we could review all of this and merge it upstream, to have LSP for ocaml/reason directly in merlin and get rid of ocaml-language-server

**Comment by andreypopp** [comment]
Cool, I suggest trying ALE with vim/neovim, this is what I have with ALE in my .vimrc:

```
function! s:get_command(buffer) abort
  return 'esy exec-command --include-current-env ocamlmerlin-lsp'
endfunction

function! s:get_language(buffer) abort
  return getbufvar(a:buffer, '&filetype')
endfunction

function! s:get_project_root(buffer) abort
  let l:merlin_file = ale#path#FindNearestFile(a:buffer, 'package.json')
  return !empty(l:merlin_file) ? fnamemodify(l:merlin_file, ':h') : ''
endfunction

call ale#linter#Define('ocaml', {
\   'name': 'merlin-lsp',
\   'lsp': 'stdio',
\   'executable_callback': function('s:executable_callback'),
\   'command_callback': function('s:get_command'),
\   'language_callback': function('s:get_language'),
\   'project_root_callback': function('s:get_project_root')
\})

call ale#linter#Define('reason', {
\   'name': 'merlin-lsp',
\   'lsp': 'stdio',
\   'executable_callback': function('s:executable_callback'),
\   'command_callback': function('s:get_command'),
\   'language_callback': function('s:get_language'),
\   'project_root_callback': function('s:get_project_root')
\})
```

**Comment by let-def** [comment]
If you are ok with that, I will try to merge your ocamlmerlin-lsp.

My plan:
- take just the code (src/lsp and src/frontend/lsp), remove the esy bits (I will keep the current opam and dune build system)
- remove dependency on ppx deriving yojson: I will include the generated code (merlin is used to develop the ocaml compiler itself, which tends to break ppx, so we would like to avoid a dependency on ppx in merlin code).

**Comment by andreypopp** [comment]
@let-def reached to you on Slack. TL;DR agree with both points but have concerns about other parts.
